"de_alive"
{
    "name"             		 	"de_alive"
    "t_arms"					"models/weapons/t_arms_phoenix.mdl"
    "ct_arms"         			"models/weapons/ct_arms_st6.mdl"
    "t_models"
			{
			"tm_phoenix_varianta" ""
			"tm_phoenix_variantb" ""
			"tm_phoenix_variantc" ""
			}
    "ct_models"
		{
    		"ctm_st6"       ""
			"ctm_st6_variantA"  ""
			"ctm_st6_variantB"  ""
			"ctm_st6_variantC"  ""
			"ctm_st6_variantD"  ""
		}
}
